name: Deploy Node/Express to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: node-express-demo-bsajhwg2ftahfndp
  NODE_VERSION: "18"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci || npm install

      # якщо немає білду — цей крок не потрібен
      # - name: Build
      #   run: npm run build

      - name: Zip artifact (optional)
        run: zip -r app.zip . -x ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
