name: Build & Deploy Node/Express to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: node-express-demo-bsajhwg2ftahfndp
  NODE_VERSION: "22.x"  # узгодь з версією в App Service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install prod deps
        run: |
          npm ci || npm install
          npm prune --omit=dev

      - name: Create deploy artifact (zip)
        run: |
          zip -r app.zip \
            server.js package.json package-lock.json node_modules \
            -x ".git/*" "**/.git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_29A78E7FC907446B854B6D8C4DB1CC21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B98AFD7D4A924A29AB1B112898B88E36 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F9C2EA78F8834ECA803D703FA209015B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip
